artifacts_root: artifacts

data_ingestion:
        root_dir : artifacts/data_Ingestion
        source_url: https://github.com/Vimlesh-17/Text-Summarizer/raw/refs/heads/main/samsum_dataset.zip
        local_data_file: artifacts/data_Ingestion/data.zip
        unzip_dir: artifacts/data_Ingestion

        